routes/web.php
        Route::get('/profile', 'Modules\Marketplaces\Backend\Marketplaces\MarketplacesController@edit')
            ->name('users.marketplaces.edit');
        Route::put('/profile', 'Modules\Marketplaces\Backend\Marketplaces\MarketplacesController@update')
            ->name('users.marketplaces.update');

        Route::resource('categories', 'Modules\Marketplaces\Backend\Marketplaces\MarketplaceCategoriesController',
            ['as'=>'users.marketplaces']);
        Route::resource('stores', 'Modules\Marketplaces\Backend\Marketplaces\StoresController', ['as'=>'users.marketplaces']);
        Route::post('stores/{store}/active', 'Modules\Marketplaces\Backend\Marketplaces\StoreActivesController@store')
            ->name('users.marketplaces.stores.active.store');
        Route::delete('stores/{store}/active', 'Modules\Marketplaces\Backend\Marketplaces\StoreActivesController@destroy')
            ->name('users.marketplaces.stores.active.destroy');

        Route::resource('banners', 'Modules\Marketplaces\Backend\Marketplaces\MarketplaceBannersController',
            ['as'=>'users.marketplaces']);
        Route::resource('banner-groups', 'Modules\Marketplaces\Backend\Marketplaces\MarketplaceBannerGroupsController',
            ['as'=>'users.marketplaces']);

        Route::post('banner-groups-details',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceBannerGroupDetailsController@store')
            ->name('users.marketplaces.banner-group-details.store');
        Route::delete('banner-groups-details/{bannerGroup}/{banner}',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceBannerGroupDetailsController@destroy')
            ->name('users.marketplaces.banner-group-details.destroy');

        Route::resource('popular-searches', 'Modules\Marketplaces\Backend\Marketplaces\MarketplacePromoPopularSearchesController',
            ['as'=>'users.marketplaces']);
        Route::get('popular-searches-imports/from-popular-searches',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplacePromoPopularSearchesController@imports')
            ->name('users.marketplaces.popular-searches.imports');
        Route::get('popular-searches-imports/from-string',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplacePromoPopularSearchesController@import')
            ->name('users.marketplaces.popular-searches.import');

        Route::resource('/store-collections',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceStoreCollectionsController',
            ['as'=>'users.marketplaces']);
        Route::post('/store-collections-details',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceStoreCollectionDetailsController@store')
            ->name('users.marketplaces.store-collection-details.store');
        Route::delete('/store-collections-details/{storeCollection}/{store}',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceStoreCollectionDetailsController@destroy')
            ->name('users.marketplaces.store-collection-details.destroy');

        Route::resource('/product-collections',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceProductCollectionsController',
            ['as'=>'users.marketplaces']);

        Route::get('/product-collection-products',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceProductCollectionProductsController@index')
            ->name('users.marketplaces.product-collections.products.index');

        Route::post('/product-collection-details',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceProductCollectionDetailsController@store')
            ->name('users.marketplaces.product-collection-details.store');
        Route::delete('/product-collection-details/{productCollection}/{product}',
            'Modules\Marketplaces\Backend\Marketplaces\MarketplaceProductCollectionDetailsController@destroy')
            ->name('users.marketplaces.product-collection-details.destroy');

        Route::resource('media-libraries', 'Modules\Marketplaces\Backend\Marketplaces\MarketplaceMediaLibrariesController', ['as'=>'users.marketplaces']);

        Route::group(['prefix' => 'settings'], function() {
            Route::get('/marketplace-settings',
                'Modules\Marketplaces\Backend\Marketplaces\MarketplaceSettingsController@edit')
                ->name('users.marketplaces.settings.marketplace-settings.edit');
            Route::put('/marketplace-settings',
                'Modules\Marketplaces\Backend\Marketplaces\MarketplaceSettingsController@update')
                ->name('users.marketplaces.settings.marketplace-settings.update');
        });
    });
});

/**
 * Administrator
 */
Route::middleware(['auth'])->group(function () {
    Route::group(['prefix' => 'administrator'], function() {
        Route::get('/', 'Modules\Administrators\AdministratorsController@index')
            ->name('administrator.index');

        /**
         * Marketplaces
         */
        Route::get('/marketplaces', 'Modules\Marketplaces\Backend\Administrators\MarketplacesController@index')
            ->name('administrator.marketplaces.index');

        Route::post('marketplaces/{marketplace}/active',
            'Modules\Marketplaces\Backend\Administrators\MarketplaceActivesController@store')
            ->name('administrator.marketplaces.active.store');
        Route::delete('marketplaces/{marketplace}/active',
            'Modules\Marketplaces\Backend\Administrators\MarketplaceActivesController@destroy')
            ->name('administrator.marketplaces.active.destroy');

        /**
         * Marketplace Collection
         */
        Route::resource('/marketplace-collections',
            'Modules\Marketplaces\Backend\Administrators\WebsiteMarketplaceCollectionsController',
            ['as'=>'administrator']);

        Route::post('/marketplace-collections-details',
            'Modules\Marketplaces\Backend\Administrators\WebsiteMarketplaceCollectionDetailsController@store')
            ->name('administrator.marketplace-collection-details.store');
        Route::delete('/marketplace-collections-details/{marketplaceCollection}/{marketplace}',
            'Modules\Marketplaces\Backend\Administrators\WebsiteMarketplaceCollectionDetailsController@destroy')
            ->name('administrator.marketplace-collection-details.destroy');

        /**
         * Product Collections
         */
        Route::resource('/product-collections',
            'Modules\Marketplaces\Backend\Administrators\WebsiteProductCollectionsController',
            ['as'=>'administrator']);

        Route::get('/product-collection-products',
            'Modules\Marketplaces\Backend\Administrators\WebsiteProductCollectionProductsController@index')
            ->name('administrator.product-collections.products.index');

        Route::post('/product-collection-details',
            'Modules\Marketplaces\Backend\Administrators\WebsiteProductCollectionDetailsController@store')
            ->name('administrator.product-collection-details.store');
        Route::delete('/product-collection-details/{productCollection}/{product}',
            'Modules\Marketplaces\Backend\Administrators\WebsiteProductCollectionDetailsController@destroy')
            ->name('administrator.product-collection-details.destroy');

        /**
         * Banners
         */
        Route::resource('/website/banners', 'Modules\Website\Backend\Administrators\WebsiteBannersController',
            ['as'=>'administrator.website']);
        Route::resource('/website/banner-groups', 'Modules\Website\Backend\Administrators\WebsiteBannerGroupsController',
            ['as'=>'administrator.website']);

        Route::post('/website/banner-groups-details',
            'Modules\Website\Backend\Administrators\WebsiteBannerGroupDetailsController@store')
            ->name('administrator.website.banner-group-details.store');
        Route::delete('/website/banner-groups-details/{bannerGroup}/{banner}',
            'Modules\Website\Backend\Administrators\WebsiteBannerGroupDetailsController@destroy')
            ->name('administrator.website.banner-group-details.destroy');

        /**
         * CMS
         */

        Route::resource('/cms/layout-elements', 'Modules\Website\Backend\Administrators\WebsiteLayoutElementsController',
            ['as'=>'administrator.website.cms']);
        Route::resource('/cms/pages', 'Modules\Website\Backend\Administrators\WebsitePagesController',
            ['as'=>'administrator.website.cms']);
        Route::resource('/cms/media-libraries', 'Modules\Website\Backend\Administrators\WebsiteMediaLibrariesController',
            ['as'=>'administrator.website.cms']);
        Route::delete('/cms/forget-caches',
            'Modules\Website\Backend\Administrators\WebsiteForgetCachesController@forgetCaches')
            ->name('administrator.website.cms.forget-caches');

        Route::resource('/cms/blog-posts', 'Modules\Website\Backend\Administrators\WebsiteBlogPostsController',
            ['as'=>'administrator.website.cms']);
        Route::resource('/cms/blog-categories', 'Modules\Website\Backend\Administrators\WebsiteBlogCategoriesController',
            ['as'=>'administrator.website.cms']);
        Route::resource('/cms/blog-banners', 'Modules\Website\Backend\Administrators\WebsiteBlogBannersController',
            ['as'=>'administrator.website.cms']);

        Route::resource('/cms/blog-post-products', 'Modules\Website\Backend\Administrators\WebsiteBlogPostProductsController',
            ['as'=>'administrator.website.cms']);

        /**
         * Settings
         */
        Route::get('/settings',
            'Modules\Website\Backend\Administrators\WebsiteSettingsController@edit')
            ->name('administrator.website.settings.edit');
        Route::put('/settings',
            'Modules\Website\Backend\Administrators\WebsiteSettingsController@update')

resources/views/modules/website/backend/administrators/cms/layout-elements/create.blade.php
@php
    /**
     * website settings
     */
    $favicon = null;
    $favicon = isset($websiteSettings['favicon']) && $websiteSettings['favicon'] ? $websiteSettings['favicon'] : false;
@endphp

@extends('themes.marika-natsuki.main')

@section('title', 'Create Layout Element')

@push('meta')
    @if ($favicon)
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset($favicon) }}">
    @endif
@endpush

@push('css')
    <link rel="stylesheet" href="{{ asset('assets/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}">
@endpush

@push('js')
    <script src="{{ asset('assets/adminlte-2.4.5/bower_components/moment/min/moment.min.js') }}"></script>
    <script src="{{ asset('assets/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>
    <script src="{{ asset('assets/plugins') }}/tinymce_4.7.9/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.datetimepicker').datetimepicker();

            /**
             * Tinymce settings
             */
            var plugins = 'preview searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern code help spellchecker';
            var toolbar1 = 'formatselect | bold italic strikethrough forecolor backcolor | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat';
            var toolbar2 = 'undo redo | link unlink image media styleselect | nanospell | fullscreen preview code ';

            tinymce.init({
                selector: '#content',
                height: 300,
                plugins: plugins,
                toolbar1: toolbar1,
                toolbar2: toolbar2,
                image_advtab: true,
                selection_toolbar: 'bold italic | quicklink h2 h3 blockquote',
                imagetools_toolbar: "rotateleft rotateright | flipv fliph | editimage imageoptions",
                content_css: [
                  '//www.tinymce.com/css/codepen.min.css',
                  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'
                ],

                relative_urls : false,
                remove_script_host : false,
                convert_urls : true,
                image_class_list: [
                    {title: 'Lazyload', value: 'lazy'},
                    {title: 'None', value: ''},
                ],

                table_default_attributes: {
                    'class': 'table table-bordered'
                },
                table_default_styles: {},
                table_class_list: [
                    {title: 'None', value: ''},
                    {title: 'Table Bordered', value: 'table table-bordered'},
                ],

                menubar:false,
            });
        });
    </script>
@endpush

@push('meta')
@endpush

@push('head_js')
@endpush

@section('content')

    @include('modules.marketplaces.frontend.inc.navbar-top-user')

    <div class="page-content">

        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">

                    <ol class="breadcrumb">
                        <li>
                            <a href="{{ route('administrator.index') }}">Home</a>
                        </li>
                        <li>
                            <a href="#">Website</a>
                        </li>
                        <li>
                            <a href="#">CMS</a>
                        </li>
                        <li>
                            <a href="{{ route('administrator.website.cms.layout-elements.index') }}">Layout Elements</a>
                        </li>
                        <li class="active">Create</li>
                    </ol>

                    <h3>Create Layout Element</h3>

                    @include('flash::message')

                    <div class="box">
                        <div class="box-content">
                            {!! Form::open([
                                'route' => ['administrator.website.cms.layout-elements.store'],
                                'method' => 'POST',
                                'files' => true,
                                ]) !!}

                                {!! Form::bs3Select('group', $dropdown['groups']) !!}
                                {!! Form::bs3Select('position', $dropdown['positions']) !!}
                                {!! Form::bs3Text('name') !!}
                                {!! Form::bs3Textarea('content') !!}
                                {!! Form::bs3Select('active', $dropdown['yes_no'], 1) !!}
                                {!! Form::bs3Number('sort_order', 1) !!}

                                {!! Form::bs3Submit('Save'); !!}
                                <a class="btn btn-default" href="{{ route('administrator.website.cms.layout-elements.index') }}">Back</a>

                            {!! Form::close() !!}
                        </div>
                    </div>

                </div>
            </div>
        </div>


    </div>

    @include('modules.administrators.backend.inc.sidebar-administrator')

    <button class="btn-back-to-top btn btn-skin" title="Go to top">
        <i class="fa fa-angle-up"></i>
    </button>

@endsection

resources/views/modules/website/backend/administrators/cms/layout-elements/edit.blade.php
@php
    /**
     * website settings
     */
    $favicon = null;
    $favicon = isset($websiteSettings['favicon']) && $websiteSettings['favicon'] ? $websiteSettings['favicon'] : false;
@endphp

@extends('themes.marika-natsuki.main')

@section('title', 'Edit Layout Element')

@push('meta')
    @if ($favicon)
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset($favicon) }}">
    @endif
@endpush

@push('css')
    <link rel="stylesheet" href="{{ asset('assets/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}">
@endpush

@push('js')
    <script src="{{ asset('assets/adminlte-2.4.5/bower_components/moment/min/moment.min.js') }}"></script>
    <script src="{{ asset('assets/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>
    <script src="{{ asset('assets/plugins') }}/tinymce_4.7.9/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.datetimepicker').datetimepicker();

            /**
             * Tinymce settings
             */
            var plugins = 'preview searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern code help spellchecker';
            var toolbar1 = 'formatselect | bold italic strikethrough forecolor backcolor | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat';
            var toolbar2 = 'undo redo | link unlink image media styleselect | nanospell | fullscreen preview code ';

            tinymce.init({
                selector: '#content',
                height: 300,
                plugins: plugins,
                toolbar1: toolbar1,
                toolbar2: toolbar2,
                image_advtab: true,
                selection_toolbar: 'bold italic | quicklink h2 h3 blockquote',
                imagetools_toolbar: "rotateleft rotateright | flipv fliph | editimage imageoptions",
                content_css: [
                  '//www.tinymce.com/css/codepen.min.css',
                  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'
                ],

                relative_urls : false,
                remove_script_host : false,
                convert_urls : true,
                image_class_list: [
                    {title: 'Lazyload', value: 'lazy'},
                    {title: 'None', value: ''},
                ],

                table_default_attributes: {
                    'class': 'table table-bordered'
                },
                table_default_styles: {},
                table_class_list: [
                    {title: 'None', value: ''},
                    {title: 'Table Bordered', value: 'table table-bordered'},
                ],

                menubar:false,
            });
        });
    </script>
@endpush

@push('meta')
@endpush

@push('head_js')
@endpush

@section('content')

    @include('modules.marketplaces.frontend.inc.navbar-top-user')

    <div class="page-content">

        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">

                    <ol class="breadcrumb">
                        <li>
                            <a href="{{ route('administrator.index') }}">Home</a>
                        </li>
                        <li>
                            <a href="#">Website</a>
                        </li>
                        <li>
                            <a href="#">CMS</a>
                        </li>
                        <li>
                            <a href="{{ route('administrator.website.cms.layout-elements.index') }}">Layout Elements</a>
                        </li>
                        <li class="active">Edit</li>
                    </ol>

                    <h3>Edit Layout Element</h3>

                    @include('flash::message')

                    <div class="box">
                        <div class="box-content">
                            {!! Form::model($layoutElement, [
                                'route' => ['administrator.website.cms.layout-elements.update', $layoutElement->id],
                                'method' => 'PUT',
                                'files' => true,
                                ]) !!}

                                {!! Form::bs3Select('group', $dropdown['groups']) !!}
                                {!! Form::bs3Select('position', $dropdown['positions']) !!}
                                {!! Form::bs3Text('name') !!}
                                {!! Form::bs3Textarea('content') !!}
                                {!! Form::bs3Select('active', $dropdown['yes_no']) !!}
                                {!! Form::bs3Number('sort_order') !!}

                                {!! Form::bs3Submit('Save'); !!}
                                <a class="btn btn-default" href="{{ route('administrator.website.cms.layout-elements.index') }}">Back</a>

                            {!! Form::close() !!}
                        </div>
                    </div>

                </div>
            </div>
        </div>


    </div>

    @include('modules.administrators.backend.inc.sidebar-administrator')

    <button class="btn-back-to-top btn btn-skin" title="Go to top">
        <i class="fa fa-angle-up"></i>
    </button>

@endsection

resources/views/modules/website/backend/administrators/cms/layout-elements/index.blade.php
@php
    /**
     * website settings
     */
    $favicon = null;
    $favicon = isset($websiteSettings['favicon']) && $websiteSettings['favicon'] ? $websiteSettings['favicon'] : false;
@endphp

@extends('themes.marika-natsuki.main')

@section('title', 'Layout Elements')

@push('meta')
    @if ($favicon)
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset($favicon) }}">
    @endif
@endpush

@push('css')
@endpush

@push('js')
    <script type="text/javascript">
        $(document).ready(function() {
            $('[data-banner-id]').on('click', function(event) {
                event.preventDefault();
                var bannerId = $(this).attr('data-banner-id');
                $('#banner_id').val(bannerId);
            });
        });
    </script>
@endpush

@push('meta')
@endpush

@push('head_js')
@endpush

@section('content')

    @include('modules.administrators.backend.inc.navbar-top-administrator')

    <div class="page-content">

        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <ol class="breadcrumb">
                        <li>
                            <a href="{{ route('administrator.index') }}">Home</a>
                        </li>
                        <li>
                            <a href="#">Website</a>
                        </li>
                        <li>
                            <a href="#">CMS</a>
                        </li>
                        <li class="active">
                            <a href="{{ route('administrator.website.cms.layout-elements.index') }}">Layout Elements</a>
                        </li>
                    </ol>

                    <h3>Layout Elements</h3>

                    @include('flash::message')
                    @include('themes.marika-natsuki.messages')

                    <a class="btn btn-primary"
                        href="{{ route('administrator.website.cms.layout-elements.create') }}">
                        Add Layout Element
                    </a>

                    {!! Form::open([
                            'route' => ['administrator.website.cms.forget-caches'],
                            'method' => 'DELETE',
                            'style' => 'display: inline-block;'
                        ]) !!}
                        {!! Form::bs3SubmitHtml('Clear Caches', ['class'=>'btn btn-danger', 'onclick'=>'return confirm("Clear?")']); !!}
                    {!! Form::close() !!}

                    <div class="box mt-3">
                        <div class="box-content">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Options</th>
                                            <th>Group</th>
                                            <th>Position</th>
                                            <th>Name</th>
                                            <th>Active</th>
                                            <th>Sort Order</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (count($layoutElements))
                                            @php
                                                $no = $layoutElements->firstItem();
                                            @endphp
                                            @foreach ($layoutElements as $element)
                                                @php
                                                    $isExpired = false;
                                                    $now = date("Y-m-d");
                                                    if ($now > $element->expired_at) {
                                                        $isExpired = true;
                                                    }
                                                    $expiredClass = 'btn btn-xs ';
                                                    $expiredClass .= ($isExpired ? ' btn-danger' : ' btn-success');
                                                @endphp
                                                <tr>
                                                    <td>{{ $no }}</td>
                                                    <td>
                                                        <a class="btn btn-xs btn-success"
                                                            href="{{ route('administrator.website.cms.layout-elements.edit', [$element->id]) }}" title="Edit">
                                                            <i class="fa fa-edit"></i>
                                                        </a>
                                                        {!! Form::open([
                                                                'route' => ['administrator.website.cms.layout-elements.destroy', $element->id],
                                                                'method' => 'DELETE',
                                                                'style' => 'display: inline-block;'
                                                            ]) !!}
                                                            {!! Form::bs3SubmitHtml('<i class="fa fa-trash"></i>', ['class'=>'btn btn-xs btn-danger', 'onclick'=>'return confirm("Delete?")']); !!}
                                                        {!! Form::close() !!}
                                                    </td>
                                                    <td>{{ $element->group }}</td>
                                                    <td>{{ $element->position }}</td>
                                                    <td>{{ $element->name }}</td>
                                                    <td>{{ $element->active ? 'Yes' : 'No' }}</td>
                                                    <td>{{ $element->sort_order }}</td>
                                                </tr>
                                                @php
                                                    $no++;
                                                @endphp
                                            @endforeach
                                        @else
                                            <tr>
                                                <td colspan="8">No data</td>
                                            </tr>
                                        @endif
                                    </tbody>
                                </table>
                            </div>
                            {{ $layoutElements->links() }}
                        </div>
                    </div>



                </div>
            </div>
        </div>
    </div>

    @include('modules.administrators.backend.inc.sidebar-administrator')

    <button class="btn-back-to-top btn btn-skin" title="Go to top">
        <i class="fa fa-angle-up"></i>
    </button>

@endsection